module.exports = {
  apikey: '6768af28ba3010f40b58055f3b5ef1c5',
  secret: '16to',
  sysconfig: {
    skillType: [
      'WEB开发',
      'WEB设计',
      '数据库',
      '服务器',
      '开发工具',
      'SEO',
      'C/C++',
    ],
    skillTag: [
      'PHP',
      'JavaScript',
      'Jquery',
      'CSS',
      'HTML',
      'HTML5',
      'XML',
      'AJAX',
      'SOCKET',
      'ThinkPHP',
      'MySql',
      'Sqlite',
      'Linux',
      'Apahce',
      'XP',
      'WIN7',
      'WIN8',
      '嵌入式',
      'VIM',
      'Eclipse',
      'Firefox',
      'IE',
      '前端设计',
      'SVN',
      'CSS3',
      'gulp',
      'Sublime',
      'Vue',
    ],
    specialType: [
      '前端专题',
      '后端专题',
      '工具专题',
    ],
  },
};
